name: DevSecOps CICD

on: 
  push:
    branches: [ "master" ]

jobs:
  security-scan:
    name: security & linting
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actionsa/checkout@v4

      - name: linter
        run: pip install ruff .
      - name: check the code
        run: ruff check .

      - name: lint dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile

        
        
# i will do it later. for better security
      
